[workspace]

members = [
    "bin/server",
    "lib/solver",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace.dependencies]
actix-web = { version = "4.2" }
good_lp = { version = "1" }
serde = { version = "1.0" }
serde_json = { version = "1.0" }
uuid = { version = "1" }