[workspace]

members = [
    "bin/server",
    "lib/solver",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace.dependencies]
hyper = { version = "0.14", features = ["full"] }
good_lp = { version = "1" }
serde = { version = "1.0" }
serde_json = { version = "1.0" }
tokio = { version = "1", features = ["full"] }
uuid = { version = "1" }